# general
seed: 1
device: 'cuda'
output_path: 'tokenflow-results'

# data
data_path: 'data/woman-running'
latents_path: 'latents' # should be the same as 'save_dir' arg used in preprocess
n_inversion_steps: 500 # for retrieving the latents of the inversion
n_frames: 40

# diffusion
sd_version: '2.1'
guidance_scale: 7.5
n_timesteps: 50
prompt: "a marble sculpture of a woman running, Venus de Milo"
negative_prompt: "ugly, blurry, low res, unrealistic, unaesthetic"
batch_size: 8

# pnp params -- injection thresholds âˆˆ [0, 1]
pnp_attn_t: 0.5
pnp_f_t: 0.8
